#!/bin/sh

if [ $# -ne 1 ]
  then
   echo -e "USAGE: $0 number\nCompute factorial of a number" >&2; exit 1
fi

re='^[0-9]+$'

if ! [[ $1 =~ $re ]] ; then
   echo "Error" >&2; exit 1
fi

factorial()
{
  i=$1
  k=1
  while [ $i -gt 1 ]
  do
	k=$(($k * $i))
	i=$(($i - 1))
  done
  echo $k
}

factorial $1

exit 0
